### PR TITLE
fix universe exploration setting + 0.7.10

### LINKED ISSUE #497: Upgrade Universe exploration (4) perk doesn't work when the mod is activated
Hello,

In a game with only this mod and its dependencies activated, and the upgrade "Universe exploration (4)", it's impossible to view the resources from all planetary systems.
We have the same issue if we load a save in solo or multiplayer mode.

If we load the same save in vanilla, the perk works as intended.

### PR DESCRIPTION
**Pull request by PhantomGamers**
closes #497

### CODE REVIEW

**Comment by PhantomGamers** [comment]
closes #497

File: NebulaPatcher/Patches/Dynamic/UIPlanetDetail_Patch.cs [hunk 1]
```diff
@@ -71,11 +68,26 @@ public static bool OnPlanetDataSet_Prefix(UIPlanetDetail __instance)
...
+            {
+                GameMain.history.universeObserveLevel = GetUniverseObserveLevel();
+            }
+        }
+
+        private static int GetUniverseObserveLevel()
+        {
+            int level = 0;
+            // the tech ids of the 4 tiers of Universe Exploration from https://dsp-wiki.com/Upgrades
+            for (int i = 4104; i >= 4101; i--)
```
Comment (mattsemar) [inline NebulaPatcher/Patches/Dynamic/UIPlanetDetail_Patch.cs:81]: Another option would be to use `i = 4` and then do `...TechUnlocked(i + 4100))`, then you could just `return i - 1` without needing mod operator.

Comment (PhantomGamers) [reply NebulaPatcher/Patches/Dynamic/UIPlanetDetail_Patch.cs:81]: Yeah but then it has to do addition each time while the mod operator only has to get called once.

Ultimately doesn't make much of a difference idk, I liked doing it this way so that it's clear that it's just going through the tech ids 4101-4104 in the loop itself

**Review by sp00ktober — APPROVED** [review]
Seems to work now on the broken save i tested with, and also seems to behave normally on my own save. Thanks for fixing this :D
